import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Muhammad Ahmad Mughal',
  description: 'Generated by create next app',
  ogImage: './images/profile/me.png',
}

const Mont = Montserrat(
  {
    subsets: ["latin"],
    variable: "--font-mont"
  }
)


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:title" content="Muhammad Ahmad Mughal" />
        <meta property="og:description" content="This is my website" />
        <meta property="og:image" content="/images/profile/me.png" />
      </Head>
      <body className={Mont.className} >{children} </body>
    </html>
  )
}
