import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Mont = Montserrat(
  {
    subsets: ["latin"],
    variable: "--font-mont"
  }
)

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Head>
        <meta name="viewport" content='width=device-width, initial-scale-1' />
        <Link rel="icon" href="/favicon.ico" />
        <link href="tailwind.css" rel="stylesheet"></link>
      </Head>

      <body className={Mont.className} >{children} </body>
    </html>
  )
}
